[package]
name = "motion_list_rs"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
name = "motion_lib"
path = "src/lib.rs"

[[bin]]
name = "yamlist"
path = "src/main.rs"

[dependencies]
byteorder = "1.3.2"
serde = { version = "1.0.98", features = ["derive"] }
serde_yaml = "0.8"