name: Rust

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: windows-latest # later, test ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --release
